apiVersion: learningcenter.tanzu.vmware.com/v1beta1
kind: TrainingPortal
metadata:
  name: tko-tmc-day1
  annotations:
    kapp.k14s.io/update-strategy: always-replace
spec:
  portal:
    ingress:
      hostname: workshop.tko.mytanzusandbox.com
    #     secret: secret-workshop
    registration:
      type: anonymous
      enabled: true
    # credentials:
    #   admin:
    #     username: admin
    #     password: Welcome11!
  workshops:
    - name: tko-day1
      capacity: 25
      expires: 300m
      orphaned: 45m
    - name: tko-day1-vcluster
      capacity: 25
      expires: 300m
      orphaned: 45m
