apiVersion: learningcenter.tanzu.vmware.com/v1beta1
kind: Workshop
metadata:
  name: tko-day1
spec:
  title: Partner Demo Workshop - Module 2
  description: Workshop created to demo the TKO Day 1 operations.
  vendor: eduk8s.io
  difficulty: beginner
  duration: 15m
  url: https://github.com/Tanzu-Partner-SE/tmc-tko-lc
  content:
    files: github.com/Tanzu-Partner-SE/tmc-tko-lc?ref=main
    image: harbor.mytanzusandbox.com/learningcenter/tko-day1:0.0.1
  session:
    namespaces:
      budget: small
    applications:
      terminal:
        enabled: true
        layout: split
      console:
        enabled: true
        vendor: octant
      editor:
        enabled: true
